### ISSUE TITLE
Formatting utility class

### ISSUE THREAD

**Issue by xunafay** [practice-enterprise/canvas-discord-bot#13]
A formatting utility class supporting Discords formatting syntax.
Example:
```ts
const msg = new Formatter()
  .bold(italic('Code block'))
  .escape('```c')
  .append('printf("Hello world!");')
  .escape('```')
  .codeBlock('ts', 'printf("Hello world!");')
  .build()
```

Note the option to call `bold` on the formatter and `italic` standalone. All functions should be callable in both forms to allow combinations

**Comment by DrunkenToast** [comment]
Will try, sounds like a good challenge.
