### ISSUE TITLE
chore: convert commands to slash commands

### ISSUE THREAD

**Issue by DrunkenToast** [practice-enterprise/canvas-discord-bot#25]
Depends on https://github.com/discordjs/discord.js/pull/5106

**Comment by DrunkenToast** [comment]
Slash commands is now out of beta.

**Comment by DrunkenToast** [comment]
Maybe just take interaction branch for slash.
Alternatively other libraries like WOKcommands or doing the work ourselves.

**Comment by DrunkenToast** [comment]
Requires rework of command handler and discord.js V13.
Out of scope for this project for now.

**Comment by PandaGamersHDNL** [comment]
discord js updated to V13

**Comment by PandaGamersHDNL** [comment]
some might not be converted because they would be useless like help -> all commands in / menu

- [ ] modules
- [x] announce
- [x] info 
- [x] notes
  - [x] guild
  - [ ] ~~global/dm~~
- [x] help deprecated
- [x] setup deprecated
- [x] prefix deprecated
- [x] ping
- [x] roll
- [x] coinflip
- [x] prefix
- [x] reminder
- [x] timezone
- [x] wiki
- [x] courses

guild commands:
- [x] rooster
- [x] code

**Comment by DrunkenToast** [comment]
Notes is done for guild, not global/dm support yet but not sure if necessary.

**Comment by PandaGamersHDNL** [comment]
add commands for updating roles and courses -> this will reduce db requests

**Comment by DrunkenToast** [comment]
> add commands for updating roles and courses -> this will reduce db requests 

I mean, aren't they event and polling based?
If event based then it's correct after oauth etc. You can just check once a day for mistake/changes.

**Comment by DrunkenToast** [comment]
Implementing caching could also solve most of the request issues (caching lastAnnounce id etc).

**Comment by PandaGamersHDNL** [comment]
> 
> 
> > add commands for updating roles and courses -> this will reduce db requests
> 
> I mean, aren't they event and polling based?
> If event based then it's correct after oauth etc. You can just check once a day for mistake/changes.

yes but most of the polling that is done isn't necessary. ex. courses should only be polled at the start of courses

**Comment by DrunkenToast** [comment]
Yes. Like I said, once day should suffice.
Update / could be implemented but seems weird from a user perspective.
