### ISSUE TITLE
Miscellaneous Commands

### ISSUE THREAD

**Issue by xunafay** [practice-enterprise/canvas-discord-bot#3]
## Hard coded
- [x] help
- [x] reminder
- [x] code block
- [x] ping
- [x] dice
- [x] Setup command

## Guild
- [x] info
  - [x] ombuds
  - [x] stuvo
  - [x] pal
- [x] notas
- [x] rooster

## Canvas
- [x] get courses/module/items (lesmateriaal)
  - [x] User friendly

**Comment by DrunkenToast** [comment]
Since we're gonna distinguish commands from hard-coded to per-guild commands we might want to make this issue properly represent that.
Edited the post to distinguish between hard-coded commands, commands that are for seperate guilds and for canvas integration

**Comment by DrunkenToast** [comment]
Setup command (depends on #29 ) for user-friendly interaction.
Canvas commands could be made more user friendly (eg. menu for selection of courses/modules, menu depends on #29 )

**Comment by PandaGamersHDNL** [comment]
schedule on rooster.thomasmore.be no api as far as i could find -> possible work around -> use the office 365 calendar instead.
https://docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0

**Comment by DrunkenToast** [comment]
> 
> 
> schedule on rooster.thomasmore.be no api as far as i could find -> possible work around -> use the office 365 calendar instead.
> https://docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0

That would require another Oauthentication or way to identify.
