### ISSUE TITLE
Automatic role assignment

### ISSUE THREAD

**Issue by DrunkenToast** [practice-enterprise/canvas-discord-bot#35]
Students get the student role.
Teachers get the teacher role.
Admins get the admin role.

User id of token holder can be found at `/api/v1/users/self`

**Comment by DrunkenToast** [comment]
Might be useful resources:
https://canvas.instructure.com/doc/api/enrollments.html
https://community.canvaslms.com/t5/Question-Forum/How-to-find-Account-Id-of-a-Canvas-user/td-p/127508

**Comment by PandaGamersHDNL** [comment]
currently only getting 1 hardcoded user -> planned: do for all users

**Comment by PandaGamersHDNL** [comment]
planned to merge the adding / deletion of roles
